# Generated by Django 6.1 on 2026-08-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='user',
            new_name='owner',
        ),
    ]
